/**
 * Generated by smali2java 1.0.0.558
 * Copyright (C) 2013 Hensence.com
 */

package com.embryo.android.speech.network.request;


import com.embryo.android.speech.SpeechSettings;
import com.embryo.speech.recognizer.api.RecognizerSessionParamsProto;

public class RecognizerSessionParamsBuilderTask extends BaseRequestBuilderTask<RecognizerSessionParamsProto.RecognizerSessionParams> {
    private final boolean mEnableAlternates;
    private final boolean mEnablePartials;
    private final boolean mProfanityFilterEnabled;
    private final int mSampleRate;
    private final SpeechSettings mSpeechSettings;

    public RecognizerSessionParamsBuilderTask(SpeechSettings speechSettings, int sampleRate, boolean enablePartials, boolean enableAlternates, boolean profanityFilterEnabled) {
        super("RecognizerSessionParamsBuilderTask");
        mSpeechSettings = speechSettings;
        mSampleRate = sampleRate;
        mEnablePartials = enablePartials;
        mEnableAlternates = enableAlternates;
        mProfanityFilterEnabled = profanityFilterEnabled;
    }

    protected RecognizerSessionParamsProto.RecognizerSessionParams build() {
        RecognizerSessionParamsProto.RecognizerSessionParams builder = new RecognizerSessionParamsProto.RecognizerSessionParams();
        builder.setType(0x0);
        builder.setMaskOffensiveWords(mProfanityFilterEnabled);
        builder.setSampleRate((float) mSampleRate);
        if (mEnablePartials) {
            builder.setEnablePartialResults(true);
        }
        return builder;
    }
}
