/**
 * Generated by smali2java 1.0.0.558
 * Copyright (C) 2013 Hensence.com
 */

package com.embryo.android.speech.message;

import com.embryo.speech.recognizer.api.RecognizerProtos;
import com.embryo.speech.s3.S3;
import com.embryo.speech.speech.s3.Recognizer;

public class S3ResponseBuilder {

    public static S3.S3Response createDone() {
        return new S3.S3Response().setStatus(0x1);
    }

    public static S3.S3Response createInProgress(RecognizerProtos.RecognitionEvent recognitionEvent) {
        return new S3.S3Response().setStatus(0x0).setRecognizerEventExtension(new Recognizer.RecognizerEvent().setRecognitionEvent(recognitionEvent));
    }

    public static S3.S3Response createWithRecognitionEvent(RecognizerProtos.RecognitionEvent event) {
        return new S3.S3Response().setStatus(0x0).setRecognizerEventExtension(new Recognizer.RecognizerEvent().setRecognitionEvent(event));
    }
}
