
/**
 * Generated by smali2java 1.0.0.558
 * Copyright (C) 2013 Hensence.com
 */

package com.embryo.android.speech.message;


import com.embryo.android.speech.listeners.RecognitionEventListener;
import com.embryo.speech.s3.S3;

public interface S3ResponseProcessor {

    public abstract void process(S3.S3Response p1, RecognitionEventListener p2);

}
