/**
 * Generated by smali2java 1.0.0.558
 * Copyright (C) 2013 Hensence.com
 */

package com.embryo.android.search.core;

import android.content.ContentResolver;
//import com.google.android.gsf.Gservices;

public class GserviceWrapper {
    private final ContentResolver mContentResolver;

    public GserviceWrapper(ContentResolver contentResolver) {
        mContentResolver = contentResolver;
    }

//    public String getString(String key) {
//        return Gservices.getString(mContentResolver, key);
//    }
}
