/**
 * Generated by smali2java 1.0.0.558
 * Copyright (C) 2013 Hensence.com
 */

package com.embryo.android.speech.alternates;

import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.util.Log;
import android.os.Bundle;
import com.embryo.android.voicesearch.logger.EventLogger;

public class SuggestionSpanBroadcastReceiver extends BroadcastReceiver {
    private static boolean DEBUG = false;
    public static Intent createIntentForEasyEditSpan(Context context, String requestId, int segmentId) {
        Intent intent = new Intent("com.google.android.speech.NOTIFY_TEXT_CHANGED");
        intent.setClass(context, SuggestionSpanBroadcastReceiver.class);
        intent.putExtra("com.google.android.speech.REQUEST_ID", requestId);
        intent.putExtra("com.google.android.speech.SEGMENT_ID", segmentId);
        return intent;
    }

    public void onReceive(Context context, Intent intent) {
        if(DEBUG) {
            Log.i("SuggestionSpanBroadcastReceiver", "#onReceive " + intent);
        }
        if("android.text.style.SUGGESTION_PICKED".equals(intent.getAction())) {
            String oldText = intent.getStringExtra("before");
            String newText = intent.getStringExtra("after");
            int suggestionId = intent.getIntExtra("hashcode", 0x0);
            if(DEBUG) {
                Log.i("SuggestionSpanBroadcastReceiver", "#onReceive " + suggestionId + " " + oldText + ">" + newText);
            }
        }
        if("com.google.android.speech.NOTIFY_TEXT_CHANGED".equals(intent.getAction())) {
            String requestId = intent.getStringExtra("com.google.android.speech.REQUEST_ID");
            if(requestId == null) {
                Log.w("SuggestionSpanBroadcastReceiver", "Missing request id");
                return;
            }
            int segmentId = intent.getIntExtra("com.google.android.speech.SEGMENT_ID", -0x1);
            if(segmentId == -0x1) {
                Log.w("SuggestionSpanBroadcastReceiver", "Missing segment id");
                return;
            }
            int changedType = intent.getIntExtra("android.text.style.EXTRA_TEXT_CHANGED_TYPE", -0x1);
            if(changedType == -0x1) {
                Log.w("SuggestionSpanBroadcastReceiver", "Missing changedType");
                return;
            }
            switch(changedType) {
                case 1:
                {
                    int eventType = 0x22;
                }
                case 2:
                {
                    int eventType = 0x10;
                    Log.w("SuggestionSpanBroadcastReceiver", "Unknown changedType " + changedType);
                    Bundle bundle = new Bundle();
                    bundle.putString("com.google.android.speech.REQUEST_ID", requestId);
                    bundle.putInt("com.google.android.speech.SEGMENT_ID", segmentId);
                    EventLogger.recordClientEvent(eventType, bundle);
                    break;
                }
            }
        }
    }
}
